config/routes.rb
Rails.application.routes.draw do


  authenticated :user do
    root to: 'tickets#index', as: :authenticated_root
    resources :users, only: [:new, :create]
  end

  unauthenticated do
    root to: 'tickets#new'
  end

  devise_for :users

  resources :tickets, param: :sub_id do #, constraints: { sub_id: /[A-Z]{3}-[0-9A-F]{2}-[A-Z]{3}-[0-9A-F]{2}-[A-Z]{3}/ }
    resources :ticket_histories, only: :create
  end
end

app/models/status.rb
class Status < ActiveRecord::Base
  enum flag: [ :initial, :waiting, :on_hold, :completed, :cancelled ]

  scope :all_completed, -> { where(flag: [flags[:completed], flags[:cancelled]]) }
  scope :open,          -> { where(flag: [flags[:initial], flags[:waiting]]) }

  has_many :ticket_histories

  validates :name, :flag,
    presence: true

  def self.initial_status
    Status.initial.first
  end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  include PgSearch

  validates :sub_id, :customer_name, :customer_email, :subject, :message,
    presence: true

  validates :sub_id,
    uniqueness: true

  after_initialize :set_sub_id, :if => :new_record?
  after_initialize :set_initial_status, :if => :new_record?

  has_many   :ticket_histories
  belongs_to :owner, class_name: User
  belongs_to :status

  scope :unassigned, -> { where(owner: nil) }
  scope :open,       -> { where(status: Status.open) }
  scope :on_hold,    -> { where(status: Status.on_hold) }
  scope :completed,  -> { where(status: Status.all_completed) }

  pg_search_scope :fulltext_search, against: [:sub_id, :subject, :message]

  def self.search(query)
    if query.present?
      fulltext_search(query)
    else
      all
    end
  end

  def to_param
    "#{sub_id}"
  end

  def set_owner!(owner)
    self.owner = owner

    self.save!
  end

  def set_status!(status)
    self.status = status

    self.save!
  end

  def owner_name
    owner.try(:name) || 'None'
  end

  private

  def set_initial_status
    self.status = Status.initial_status
  end

  def set_sub_id
    self.sub_id = "#{random_chars}-#{SecureRandom.hex(1)}-#{random_chars}-#{SecureRandom.hex(1)}-#{random_chars}".upcase
  end

  def random_chars
    # Thanks to stackoverflow :)
    (0...3).map { (65 + rand(26)).chr }.join
  end
end

app/models/ticket_history.rb
class TicketHistory < ActiveRecord::Base
  belongs_to :ticket
  belongs_to :user
  belongs_to :owner, class_name: User
  belongs_to :status

  validates :ticket, :user, :status, :message,
    presence: true

  before_validation :set_last_status, :if => proc { self.status.nil? }
  after_save        :set_status_for_ticket
  after_save        :set_owner_for_ticket

  def owner_name
    owner.try(:name) || 'None'
  end

  private

  def set_owner_for_ticket
    self.ticket.set_owner! owner
  end

  def set_status_for_ticket
    self.ticket.set_status! status
  end

  def set_last_status
    self.status ||= ticket.status
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :recoverable, :rememberable,
         :trackable, :validatable

  enum role: [:staff, :customer, :admin]

  after_initialize :set_default_role, :if => :new_record?

  has_many :ticket_histories
  has_many :tickets, foreign_key: :owner_id

  def can_edit?
    staff? or admin?
  end

  def self.customer_user
    User.customer.first
  end

  private

  def set_default_role
    self.role ||= :staff
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_admin!
    unless user_signed_in? && current_user.admin?
      flash[:error] = "You are not an administrator!"
      redirect_to :root
    end
  end
end

app/controllers/ticket_histories_controller.rb
class TicketHistoriesController < ApplicationController
  before_action :set_ticket

  respond_to :html

  def create
    if user_signed_in? && current_user.can_edit?
      create_by_staff
    else
      create_by_customer
    end

    flash[:error] = @ticket_history.errors.full_messages.join(', ') unless @ticket.valid?

    redirect_to @ticket
  end

  def create_by_customer
    @ticket_history = @ticket.ticket_histories.new(user_ticket_params)
    @ticket_history.user = User.customer_user
    @ticket_history.status = Status.initial_status

    @ticket_history.save
  end

  def create_by_staff
    @ticket_history = @ticket.ticket_histories.new(ticket_params)
    @ticket_history.user = current_user

    TicketMailer.notify(@ticket_history).deliver if @ticket_history.save
  end

  private

  def set_ticket
    @ticket = Ticket.find_by! sub_id: params[:ticket_sub_id]
  end

  def ticket_params
    params.require(:ticket_history).permit(:message, :status_id, :owner_id)
  end

  def user_ticket_params
    params.require(:ticket_history).permit(:message)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :update]
  before_filter :authenticate_user!, only: [:index, :update]

  respond_to :html

  def index
    @tickets = Ticket.send(determine_search_scope).search(params[:search]).order(:created_at)
  end

  def show
    @ticket_history = TicketHistory.new
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)
    if @ticket.save
      TicketMailer.confirm(@ticket).deliver
      redirect_to @ticket
    else
      render :new
    end
  end

  def update
    @ticket.update(ticket_params)
  end

  private

  def determine_search_scope
    scope = params[:status].try(:to_sym) || :all
    [:unassigned, :open, :on_hold, :completed, :all].include?(scope) ? scope : :all
  end

  def set_ticket
    @ticket = Ticket.includes(:ticket_histories).find_by! sub_id: params[:sub_id]
  end

  def ticket_params
    params.require(:ticket).permit(:customer_name, :customer_email, :subject, :message)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :authenticate_admin!

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.role = :staff

    if @user.save
      flash[:notice] = "User #{@user.name} created!"
      redirect_to new_user_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{class: "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, id: "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'
      - if user_signed_in?
        = render 'tickets/search_form'
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          - if current_user.admin?
            %li= link_to "Add User", new_user_path
          %li= link_to 'Sign out', destroy_user_session_path, method: 'delete'
        - else
          %li= link_to 'Sign in', new_user_session_path

app/views/layouts/_navigation_links.html.haml
- if user_signed_in?
  %li.dropdown
    %a.dropdown-toggle{ "aria-expanded" => "false", "data-toggle" => "dropdown", href: "#", role: "button" }
      Tickets
      %span.caret
    %ul.dropdown-menu{ role: "menu" }
      %li= link_to "All tickets", tickets_path
      %li= link_to "New unassigned tickets", tickets_path(status: :unassigned)
      %li= link_to "Open Tickets", tickets_path(status: :open)
      %li= link_to "On hold tickets", tickets_path(status: :on_hold)
      %li= link_to "Closed Tickets", tickets_path(status: :completed)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }
    %title= content_for?(:title) ? yield(:title) : 'Issue Tracker'
    %meta{ name: "description", content: "#{content_for?(:description) ? yield(:description) : 'Issue Tracker'}" }
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{role: "main"}
      = render 'layouts/messages'
      = yield

app/views/ticket_histories/_form.html.haml
= form_for [@ticket, @ticket_history] do |f|
  - if @ticket_history.errors.any?
    #error_explanation
      %h2= "#{pluralize(@ticket_history.errors.count, "error")} prohibited this ticket from being saved:"
      %ul
        - @ticket_history.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :status_id
    = f.select :status_id, Status.all.map{|s| [s.name, s.id]}, { selected: @ticket.status_id }, { class: 'form-control'}
  .form-group
    = f.label :owner_id
    = f.select :owner_id, User.staff.map{|u| [u.name, u.id]}, { selected: @ticket.owner_id, include_blank: "None" }, { class: 'form-control' }
  .form-group
    = f.label :message
    = f.text_area :message, class: 'form-control'
  .form-group
    = f.submit 'Save', class: 'btn btn-success'

app/views/ticket_histories/_index.html.haml
%h3 History

%table.table.table-striped
  %thead
    %tr
      %th Message
      %th Status
      %th User
      %th Owner

  %tbody
    - @ticket.ticket_histories.each do |ticket_history|
      %tr
        %td= ticket_history.message
        %td= ticket_history.status.name
        %td= ticket_history.user.name
        %td= ticket_history.owner_name

app/views/ticket_histories/_user_form.html.haml
= form_for [@ticket, @ticket_history] do |f|
  - if @ticket_history.errors.any?
    #error_explanation
      %h2= "#{pluralize(@ticket_history.errors.count, "error")} prohibited this ticket from being saved:"
      %ul
        - @ticket_history.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :message
    = f.text_area :message, class: 'form-control'
  .form-group
    = f.submit 'Save', class: 'btn btn-success'

app/views/tickets/_form.html.haml
= form_for @ticket do |f|
  - if @ticket.errors.any?
    #error_explanation
      %h2= "#{pluralize(@ticket.errors.count, "error")} prohibited this ticket from being saved:"
      %ul
        - @ticket.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :customer_name
    = f.text_field :customer_name, class: 'form-control'
  .form-group
    = f.label :customer_email
    = f.text_field :customer_email, class: 'form-control'
  .form-group
    = f.label :subject
    = f.text_field :subject, class: 'form-control'
  .form-group
    = f.label :message
    = f.text_area :message, class: 'form-control'
  .form-group
    = f.submit 'Save', class: 'btn btn-success'

app/views/tickets/_search_form.html.haml
= form_tag tickets_path(status: params[:status]), class: "navbar-form navbar-left", role: :search, method: :get do
  .form-group
    = hidden_field_tag 'status', params[:status]
    = text_field_tag :search, params[:search], placeholder: "Search", class: "form-control"
    = submit_tag 'Search', class: "btn btn-default"

app/views/tickets/index.html.haml
%h1 Listing tickets

%table.table.table-striped
  %thead
    %tr
      %th Id
      %th Subject
      %th Customer name
      %th Status
      %th Owner

  %tbody
    - @tickets.each do |ticket|
      %tr
        %td= link_to ticket.sub_id, ticket
        %td= ticket.subject
        %td= ticket.customer_name
        %td= ticket.status.name
        %td= ticket.owner_name

%br

= link_to 'New Ticket', new_ticket_path, class: "btn btn-primary"

app/views/tickets/new.html.haml
%h1 New ticket

= render 'form'

- if user_signed_in?
  %br
  = link_to 'Back', tickets_path, class: "btn btn-primary"

app/views/tickets/show.html.haml
%p#notice= notice


%dl.dl-horizontal
  %dt Sub:
  %dd= @ticket.sub_id

  %dt Status:
  %dd= @ticket.status.name

  %dt Customer name:
  %dd= @ticket.customer_name

  %dt Customer email:
  %dd= @ticket.customer_email

  %dt Subject:
  %dd= @ticket.subject

  %dt Message:
  %dd= @ticket.message

  %dt Owner:
  %dd= @ticket.owner_name


= render 'ticket_histories/index'

- if user_signed_in? && current_user.can_edit?
  = render 'ticket_histories/form'
  = link_to 'Back', tickets_path, class: "btn btn-primary"
- else
  = render 'ticket_histories/user_form'

app/views/users/new.html.haml
%h1 Create staff user

= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this ticket from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :email
    = f.text_field :email, class: 'form-control'
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :password
    = f.text_field :password, class: 'form-control'
  .form-group
    = f.submit 'Save', class: 'btn btn-success'